//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Improview.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveFile", ReplyAction="http://tempuri.org/IService1/SaveFileResponse")]
        string SaveFile(string guid, string filename, byte[] sentFile);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/SaveFile", ReplyAction="http://tempuri.org/IService1/SaveFileResponse")]
        System.IAsyncResult BeginSaveFile(string guid, string filename, byte[] sentFile, System.AsyncCallback callback, object asyncState);
        
        string EndSaveFile(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Improview.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Improview.ServiceReference1.IService1>, Improview.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginSaveFileDelegate;
        
        private EndOperationDelegate onEndSaveFileDelegate;
        
        private System.Threading.SendOrPostCallback onSaveFileCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<SaveFileCompletedEventArgs> SaveFileCompleted;
        
        public string SaveFile(string guid, string filename, byte[] sentFile) {
            return base.Channel.SaveFile(guid, filename, sentFile);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSaveFile(string guid, string filename, byte[] sentFile, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveFile(guid, filename, sentFile, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndSaveFile(System.IAsyncResult result) {
            return base.Channel.EndSaveFile(result);
        }
        
        private System.IAsyncResult OnBeginSaveFile(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string guid = ((string)(inValues[0]));
            string filename = ((string)(inValues[1]));
            byte[] sentFile = ((byte[])(inValues[2]));
            return this.BeginSaveFile(guid, filename, sentFile, callback, asyncState);
        }
        
        private object[] OnEndSaveFile(System.IAsyncResult result) {
            string retVal = this.EndSaveFile(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveFileCompleted(object state) {
            if ((this.SaveFileCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveFileCompleted(this, new SaveFileCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveFileAsync(string guid, string filename, byte[] sentFile) {
            this.SaveFileAsync(guid, filename, sentFile, null);
        }
        
        public void SaveFileAsync(string guid, string filename, byte[] sentFile, object userState) {
            if ((this.onBeginSaveFileDelegate == null)) {
                this.onBeginSaveFileDelegate = new BeginOperationDelegate(this.OnBeginSaveFile);
            }
            if ((this.onEndSaveFileDelegate == null)) {
                this.onEndSaveFileDelegate = new EndOperationDelegate(this.OnEndSaveFile);
            }
            if ((this.onSaveFileCompletedDelegate == null)) {
                this.onSaveFileCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveFileCompleted);
            }
            base.InvokeAsync(this.onBeginSaveFileDelegate, new object[] {
                        guid,
                        filename,
                        sentFile}, this.onEndSaveFileDelegate, this.onSaveFileCompletedDelegate, userState);
        }
    }
}
